package com.learnchemistry.createsciences.chemistry.catalog;

import java.util.List;

public final class PeriodicElements {
    private PeriodicElements() {
    }

    public static ElementCatalog createCatalog() {
        return new ElementCatalog(List.of(
                element(1, "H", "Hydrogen"),
                element(2, "He", "Helium"),
                element(3, "Li", "Lithium"),
                element(4, "Be", "Beryllium"),
                element(5, "B", "Boron"),
                element(6, "C", "Carbon"),
                element(7, "N", "Nitrogen"),
                element(8, "O", "Oxygen"),
                element(9, "F", "Fluorine"),
                element(10, "Ne", "Neon"),
                element(11, "Na", "Sodium"),
                element(12, "Mg", "Magnesium"),
                element(13, "Al", "Aluminium"),
                element(14, "Si", "Silicon"),
                element(15, "P", "Phosphorus"),
                element(16, "S", "Sulfur"),
                element(17, "Cl", "Chlorine"),
                element(18, "Ar", "Argon"),
                element(19, "K", "Potassium"),
                element(20, "Ca", "Calcium"),
                element(21, "Sc", "Scandium"),
                element(22, "Ti", "Titanium"),
                element(23, "V", "Vanadium"),
                element(24, "Cr", "Chromium"),
                element(25, "Mn", "Manganese"),
                element(26, "Fe", "Iron"),
                element(27, "Co", "Cobalt"),
                element(28, "Ni", "Nickel"),
                element(29, "Cu", "Copper"),
                element(30, "Zn", "Zinc"),
                element(31, "Ga", "Gallium"),
                element(32, "Ge", "Germanium"),
                element(33, "As", "Arsenic"),
                element(34, "Se", "Selenium"),
                element(35, "Br", "Bromine"),
                element(36, "Kr", "Krypton"),
                element(37, "Rb", "Rubidium"),
                element(38, "Sr", "Strontium"),
                element(39, "Y", "Yttrium"),
                element(40, "Zr", "Zirconium"),
                element(41, "Nb", "Niobium"),
                element(42, "Mo", "Molybdenum"),
                element(43, "Tc", "Technetium"),
                element(44, "Ru", "Ruthenium"),
                element(45, "Rh", "Rhodium"),
                element(46, "Pd", "Palladium"),
                element(47, "Ag", "Silver"),
                element(48, "Cd", "Cadmium"),
                element(49, "In", "Indium"),
                element(50, "Sn", "Tin"),
                element(51, "Sb", "Antimony"),
                element(52, "Te", "Tellurium"),
                element(53, "I", "Iodine"),
                element(54, "Xe", "Xenon"),
                element(55, "Cs", "Caesium"),
                element(56, "Ba", "Barium"),
                element(57, "La", "Lanthanum"),
                element(58, "Ce", "Cerium"),
                element(59, "Pr", "Praseodymium"),
                element(60, "Nd", "Neodymium"),
                element(61, "Pm", "Promethium"),
                element(62, "Sm", "Samarium"),
                element(63, "Eu", "Europium"),
                element(64, "Gd", "Gadolinium"),
                element(65, "Tb", "Terbium"),
                element(66, "Dy", "Dysprosium"),
                element(67, "Ho", "Holmium"),
                element(68, "Er", "Erbium"),
                element(69, "Tm", "Thulium"),
                element(70, "Yb", "Ytterbium"),
                element(71, "Lu", "Lutetium"),
                element(72, "Hf", "Hafnium"),
                element(73, "Ta", "Tantalum"),
                element(74, "W", "Tungsten"),
                element(75, "Re", "Rhenium"),
                element(76, "Os", "Osmium"),
                element(77, "Ir", "Iridium"),
                element(78, "Pt", "Platinum"),
                element(79, "Au", "Gold"),
                element(80, "Hg", "Mercury"),
                element(81, "Tl", "Thallium"),
                element(82, "Pb", "Lead"),
                element(83, "Bi", "Bismuth"),
                element(84, "Po", "Polonium"),
                element(85, "At", "Astatine"),
                element(86, "Rn", "Radon"),
                element(87, "Fr", "Francium"),
                element(88, "Ra", "Radium"),
                element(89, "Ac", "Actinium"),
                element(90, "Th", "Thorium"),
                element(91, "Pa", "Protactinium"),
                element(92, "U", "Uranium"),
                element(93, "Np", "Neptunium"),
                element(94, "Pu", "Plutonium"),
                element(95, "Am", "Americium"),
                element(96, "Cm", "Curium"),
                element(97, "Bk", "Berkelium"),
                element(98, "Cf", "Californium"),
                element(99, "Es", "Einsteinium"),
                element(100, "Fm", "Fermium"),
                element(101, "Md", "Mendelevium"),
                element(102, "No", "Nobelium"),
                element(103, "Lr", "Lawrencium"),
                element(104, "Rf", "Rutherfordium"),
                element(105, "Db", "Dubnium"),
                element(106, "Sg", "Seaborgium"),
                element(107, "Bh", "Bohrium"),
                element(108, "Hs", "Hassium"),
                element(109, "Mt", "Meitnerium"),
                element(110, "Ds", "Darmstadtium"),
                element(111, "Rg", "Roentgenium"),
                element(112, "Cn", "Copernicium"),
                element(113, "Nh", "Nihonium"),
                element(114, "Fl", "Flerovium"),
                element(115, "Mc", "Moscovium"),
                element(116, "Lv", "Livermorium"),
                element(117, "Ts", "Tennessine"),
                element(118, "Og", "Oganesson")
        ));
    }

    private static ElementDefinition element(int atomicNumber, String symbol, String displayName) {
        return new ElementDefinition(atomicNumber, symbol, displayName);
    }
}
